AllCops:
  NewCops: enable
  SuggestExtensions: false

# minimal personal preference
Layout/EndAlignment: { EnforcedStyleAlignWith: variable }
Lint/AssignmentInCondition: { Enabled: false }
Metrics: { Enabled: false }
Naming/MethodParameterName: { Enabled: false }
Naming/VariableNumber: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/FrozenStringLiteralComment: { Enabled: false }
Style/IfUnlessModifier: { Enabled: false }
Style/NegatedIf: { Enabled: false }
Style/StderrPuts: { Enabled: false }
Style/TrailingCommaInArrayLiteral: { EnforcedStyleForMultiline: consistent_comma }
Style/TrailingCommaInHashLiteral: { EnforcedStyleForMultiline: consistent_comma }
