require:
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

# a couple of overrides
Style/RedundantReturn: { Enabled: false }
Style/HashSyntax: { EnforcedShorthandSyntax: always }
